/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
// TAMBAHKAN BARIS IMPORT INI DI SINI:
import model.Buku;

/**
 *
 * @author HYPE AMD
 */
public final class FormBukuAdvanced extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormBukuAdvanced.class.getName());

    // 1. LETAKKAN DEKLARASI CONTROLLER DI SINI (Tepat di bawah logger)
    controller.BukuController controller = new controller.BukuController();

    /**
     * Creates new form FormBukuAdvanced
     */
    public FormBukuAdvanced() {
        initComponents();
        // Memanggil fungsi refresh tabel saat aplikasi pertama kali dibuka
        new Thread(() -> tampilkanDataTabel()).start();
}

    // METHOD REFRESH YANG SUDAH DISESUAIKAN DENGAN CONTROLLER-MU
    public void tampilkanDataTabel() {
        try {
            // Mengeset model tblBuku menggunakan fungsi getModelBuku() dari controller
            tblBuku.setModel(controller.getModelBuku()); 
            
            // TAMBAHKAN BARIS INI: Jika berhasil konek dan load data
            lblStatus.setText("Status : Database Connected");
            lblStatus.setForeground(java.awt.Color.BLACK);
            
        } catch (Exception e) {
            // TAMBAHKAN BARIS INI: Jika gagal koneksi database
            lblStatus.setText("Status : Database Connection Failed!");
            lblStatus.setForeground(java.awt.Color.RED);
            
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panelForm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtJudul = new javax.swing.JTextField();
        txtPenulis = new javax.swing.JTextField();
        txtTahun = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtStok = new javax.swing.JTextField();
        panelButon = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        panelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuku = new javax.swing.JTable();
        panelStatus = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        itemDataBuku = new javax.swing.JMenu();
        itemReport = new javax.swing.JMenu();
        itemExit = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelHeader.setBackground(new java.awt.Color(0, 102, 102));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("APLIKASI PERPUSTAKAAN DIGITAL");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelForm.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setText("ID Buku");

        txtId.addActionListener(this::txtIdActionPerformed);

        jLabel2.setText("Judul Buku");

        jLabel3.setText("Tahun");

        jLabel4.setText("Penulis");

        txtJudul.addActionListener(this::txtJudulActionPerformed);

        txtPenulis.addActionListener(this::txtPenulisActionPerformed);

        txtTahun.addActionListener(this::txtTahunActionPerformed);

        jLabel5.setText("Jumlah Stok");

        txtStok.addActionListener(this::txtStokActionPerformed);

        javax.swing.GroupLayout panelFormLayout = new javax.swing.GroupLayout(panelForm);
        panelForm.setLayout(panelFormLayout);
        panelFormLayout.setHorizontalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(78, 78, 78)
                        .addComponent(txtTahun))
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(69, 69, 69)
                        .addComponent(txtId))
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(53, 53, 53)
                        .addComponent(txtJudul))
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(73, 73, 73)
                        .addComponent(txtPenulis))
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(46, 46, 46)
                        .addComponent(txtStok))))
        );
        panelFormLayout.setVerticalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelButon.setBackground(new java.awt.Color(204, 255, 204));

        btnRefresh.setText("refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        btnDelete.setText("delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnEdit.setText("edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnSimpan.setText("simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        javax.swing.GroupLayout panelButonLayout = new javax.swing.GroupLayout(panelButon);
        panelButon.setLayout(panelButonLayout);
        panelButonLayout.setHorizontalGroup(
            panelButonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelButonLayout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(btnSimpan)
                .addGap(18, 18, 18)
                .addComponent(btnEdit)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addGap(18, 18, 18)
                .addComponent(btnRefresh)
                .addGap(27, 27, 27))
        );
        panelButonLayout.setVerticalGroup(
            panelButonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelButonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelButonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit)
                    .addComponent(btnSimpan))
                .addContainerGap())
        );

        panelTable.setBackground(new java.awt.Color(153, 102, 255));

        tblBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Judul", "Penulis", "Tahun", "Stok"
            }
        ));
        tblBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBuku);

        javax.swing.GroupLayout panelTableLayout = new javax.swing.GroupLayout(panelTable);
        panelTable.setLayout(panelTableLayout);
        panelTableLayout.setHorizontalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTableLayout.setVerticalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelStatus.setBackground(new java.awt.Color(0, 102, 102));

        lblStatus.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblStatus.setText("Status : Disconnected");

        javax.swing.GroupLayout panelStatusLayout = new javax.swing.GroupLayout(panelStatus);
        panelStatus.setLayout(panelStatusLayout);
        panelStatusLayout.setHorizontalGroup(
            panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelStatusLayout.setVerticalGroup(
            panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatus)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        itemDataBuku.setText("Data Buku");
        itemDataBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemDataBukuMouseClicked(evt);
            }
        });
        jMenuBar1.add(itemDataBuku);

        itemReport.setText("Report");
        itemReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemReportMouseClicked(evt);
            }
        });
        jMenuBar1.add(itemReport);

        itemExit.setText("Exit");
        itemExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemExitMouseClicked(evt);
            }
        });
        jMenuBar1.add(itemExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelButon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJudulActionPerformed

    private void txtPenulisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPenulisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPenulisActionPerformed

    private void txtTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTahunActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
try {
    // 1. Ambil data dari masing-masing JTextField Form
    int id = Integer.parseInt(txtId.getText());
    String judul = txtJudul.getText();
    String penulis = txtPenulis.getText();
    int tahun = Integer.parseInt(txtTahun.getText());
    int stok = Integer.parseInt(txtStok.getText());

    // 2. Bungkus ke dalam objek Model Buku
    Buku bukuBaru = new Buku();
    bukuBaru.setId(id);
    bukuBaru.setJudul(judul);
    bukuBaru.setPenulis(penulis);
    bukuBaru.setTahun(tahun);
    bukuBaru.setStok(stok);

    // 3. Panggil method insert dari controller-mu
    controller.tambahBuku(bukuBaru);

    // 4. Refresh tabel agar data baru langsung muncul
    tampilkanDataTabel();
    
    // 5. MANUAL RESET FORM (Menggantikan baris 319 yang error)
    txtId.setText("");
    txtJudul.setText("");
    txtPenulis.setText("");
    txtTahun.setText("");
    txtStok.setText("");
    txtId.setEnabled(true);
    txtId.requestFocus();
    
    javax.swing.JOptionPane.showMessageDialog(this, "Data buku berhasil disimpan!");
} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "ID, Tahun, dan Stok harus berupa angka!");
}
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStokActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
txtId.setText("");
txtJudul.setText("");
txtPenulis.setText("");
txtTahun.setText("");
txtStok.setText("");

// Mengaktifkan kembali kolom ID (jika sebelumnya kekunci pas klik tabel)
txtId.setEnabled(true);
txtId.requestFocus();

// Segarkan data tabel
tampilkanDataTabel();        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tblBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBukuMouseClicked
int baris = tblBuku.getSelectedRow();
if (baris != -1) {
    // Memindahkan data dari tabel ke text field
    txtId.setText(tblBuku.getValueAt(baris, 0).toString());
    txtJudul.setText(tblBuku.getValueAt(baris, 1).toString());
    txtPenulis.setText(tblBuku.getValueAt(baris, 2).toString());
    txtTahun.setText(tblBuku.getValueAt(baris, 3).toString());
    txtStok.setText(tblBuku.getValueAt(baris, 4).toString());
    
    // Kunci kolom ID agar tidak bisa diedit karena merupakan Primary Key
    txtId.setEnabled(false);
}        // TODO add your handling code here:
    }//GEN-LAST:event_tblBukuMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
try {
    if (txtId.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih dulu data buku yang ingin diedit dari tabel!");
        return;
    }
    
    int id = Integer.parseInt(txtId.getText());
    int stokBaru = Integer.parseInt(txtStok.getText());
    
    // Panggil fungsi update dari controller-mu
    controller.updateStok(id, stokBaru);
    
    // Refresh & Bersihkan Form
    tampilkanDataTabel();
    
    txtId.setText("");
    txtJudul.setText("");
    txtPenulis.setText("");
    txtTahun.setText("");
    txtStok.setText("");
    txtId.setEnabled(true);
    
    javax.swing.JOptionPane.showMessageDialog(this, "Stok buku berhasil diperbarui!");
} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Stok harus berupa angka!");
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
if (txtId.getText().isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Pilih dulu data buku yang ingin dihapus dari tabel!");
    return;
}

int pilihan = javax.swing.JOptionPane.showConfirmDialog(this, 
        "Apakah Anda yakin ingin menghapus buku ini?", "Konfirmasi Hapus", 
        javax.swing.JOptionPane.YES_NO_OPTION);

if (pilihan == javax.swing.JOptionPane.YES_OPTION) {
    int id = Integer.parseInt(txtId.getText());
    
    // Panggil fungsi hapus dari controller-mu
    controller.hapusBuku(id);
    
    // Refresh & Bersihkan Form
    tampilkanDataTabel();
    
    txtId.setText("");
    txtJudul.setText("");
    txtPenulis.setText("");
    txtTahun.setText("");
    txtStok.setText("");
    txtId.setEnabled(true);
    
    javax.swing.JOptionPane.showMessageDialog(this, "Data buku berhasil dihapus!");
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void itemDataBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemDataBukuMouseClicked
// Memanggil ulang data dari database ke JTable
tampilkanDataTabel();

// Mengosongkan form inputan kembali
txtId.setText("");
txtJudul.setText("");
txtPenulis.setText("");
txtTahun.setText("");
txtStok.setText("");

// Mengaktifkan kembali field ID buku jika sebelumnya terkunci
txtId.setEnabled(true);

javax.swing.JOptionPane.showMessageDialog(this, 
    "Halaman Data Buku berhasil disegarkan.", 
    "Informasi", 
    javax.swing.JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_itemDataBukuMouseClicked

    private void itemExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemExitMouseClicked
int pilihan = javax.swing.JOptionPane.showConfirmDialog(
        this, 
        "Apakah Anda yakin ingin keluar dari sistem aplikasi perpustakaan?", 
        "Konfirmasi Keluar", 
        javax.swing.JOptionPane.YES_NO_OPTION,
        javax.swing.JOptionPane.QUESTION_MESSAGE
);

if (pilihan == javax.swing.JOptionPane.YES_OPTION) {
    System.exit(0); // Menutup program secara total
}        // TODO add your handling code here:
    }//GEN-LAST:event_itemExitMouseClicked

    private void itemReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemReportMouseClicked
// 1. Validasi jika data tabel masih kosong
if (tblBuku.getRowCount() == 0) {
    javax.swing.JOptionPane.showMessageDialog(this, 
        "Data masih kosong! Tidak ada yang bisa dicetak.", 
        "Peringatan", 
        javax.swing.JOptionPane.WARNING_MESSAGE);
    return; 
}

// 2. Tampilkan pilihan opsi laporan
String[] opsi = {"Export ke CSV", "Print Tabel Langsung", "Batal"};
int pilihan = javax.swing.JOptionPane.showOptionDialog(
        this,
        "Pilih format keluaran laporan yang diinginkan:",
        "Modul Pelaporan (Advanced)",
        javax.swing.JOptionPane.DEFAULT_OPTION,
        javax.swing.JOptionPane.QUESTION_MESSAGE,
        null,
        opsi,
        opsi[0]
);

// JIKA USER MEMILIH EXPORT KE CSV
if (pilihan == 0) {
    javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    fileChooser.setDialogTitle("Simpan Laporan CSV");
    
    int userSelection = fileChooser.showSaveDialog(this);
    if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
        try {
            String path = fileChooser.getSelectedFile().getAbsolutePath();
            // Memastikan file berakhiran ekstensi .csv
            if (!path.toLowerCase().endsWith(".csv")) {
                path += ".csv";
            }
            
            java.io.FileWriter writer = new java.io.FileWriter(path);
            
            // Tulis Header Kolom di file CSV
            writer.write("ID,JUDUL,PENULIS,TAHUN,STOK\n");
            
            // Looping mengambil isi baris dan kolom JTable untuk ditulis ke file CSV
            for (int i = 0; i < tblBuku.getRowCount(); i++) {
                for (int j = 0; j < tblBuku.getColumnCount(); j++) {
                    Object cellValue = tblBuku.getValueAt(i, j);
                    writer.write(cellValue != null ? cellValue.toString() : "");
                    
                    if (j < tblBuku.getColumnCount() - 1) {
                        writer.write(","); // Pemisah kolom csv
                    }
                }
                writer.write("\n"); // Baris baru
            }
            writer.close();
            javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil diekspor ke format CSV!");
        } catch (java.io.IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan sistem: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
} 
// JIKA USER MEMILIH PRINT TABEL LANGSUNG
else if (pilihan == 1) {
    java.text.MessageFormat header = new java.text.MessageFormat("--- REKAPITULASI DATA BUKU ---");
    java.text.MessageFormat footer = new java.text.MessageFormat("Sistem Informasi Perpustakaan | Halaman {0,number,integer}");
    try {
        boolean sukses = tblBuku.print(
            javax.swing.JTable.PrintMode.FIT_WIDTH, 
            header, 
            footer, 
            true, 
            null, 
            true, 
            null
        );
        if (sukses) {
            javax.swing.JOptionPane.showMessageDialog(this, "Dokumen berhasil diproses ke antrean cetak.");
        }
    } catch (java.awt.print.PrinterException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal mencetak: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}        // TODO add your handling code here:
    }//GEN-LAST:event_itemReportMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormBukuAdvanced().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JMenu itemDataBuku;
    private javax.swing.JMenu itemExit;
    private javax.swing.JMenu itemReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel panelButon;
    private javax.swing.JPanel panelForm;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelStatus;
    private javax.swing.JPanel panelTable;
    private javax.swing.JTable tblBuku;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtPenulis;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtTahun;
    // End of variables declaration//GEN-END:variables
}
